import "./globals.css";
import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import Providers from "@/components/ui/Provider";
import { ClerkProvider, auth } from "@clerk/nextjs";
//-----------------------------------
import { Roboto } from "next/font/google";

const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
});
//-------------------------------------

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ecom Hackathon",
  description: "Generated by Next",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { userId } = auth();
  return (
    <html lang="en">
      <ClerkProvider>
        <Providers>
          <body className={roboto.className}>
            <main>
              <Header userId={userId as string} />

              {children}
              <Footer />
            </main>
          </body>
        </Providers>
      </ClerkProvider>
    </html>
  );
}
